const MC_SPRITES_ENTITYS = {
    "黑色凋零骷" : "WITHER_SKELETON",
    "炸药凋灵骷" : "WITHER_SKULL",
    "尸壳" : "HUSK",
    "僵尸村民" : "ZOMBIE_VILLAGER",
    "骷髅马" : "SKELETON_HORSE",
    "僵尸马" : "ZOMBIE_HORSE",
    "苦力怕" : "CREEPER",
    "骷髅" : "SKELETON",
    "蜘蛛" : "SPIDER",
    "巨人" : "GIANT",
    "僵尸" : "ZOMBIE",
    "史莱姆" : "SLIME",
    "恶魂" : "GHAST",
    "僵尸猪人" : "PIG_ZOMBIE",
    "末影人" : "ENDERMAN",
    "洞穴蜘蛛" : "CAVE_SPIDER",
    "末影龙" : "ENDER_DRAGON",
    "凋零" : "WITHER",
    "蝙蝠" : "BAT",
    "女巫" : "WITCH",
    "猪" : "PIG",
    "绵羊" : "SHEEP",
    "牛" : "COW",
    "鸡" : "CHICKEN",
    "鱿鱼" : "SQUID",
    "狼" : "WOLF",
    "蘑菇牛" : "MUSHROOM_COW",
    "雪人" : "SNOWMAN",
    "豹猫" : "OCELOT",
    "铁傀儡" : "IRON_GOLEM",
    "马" : "HORSE",
    "兔子" : "RABBIT",
    "北极熊" : "POLAR_BEAR",
    "羊驼" : "LLAMA",
    "羊驼的口水" : "LLAMA_SPIT",
    "鹦鹉" : "PARROT",
    "村民" : "VILLAGER",
}

export {MC_SPRITES_ENTITYS}